### ISSUE TITLE
Recipes Tables

### ISSUE THREAD

**Issue by jeffhennen** [ZachSellman/hennen_recipes#16]
For this, we will need to create tables that will store the corresponding recipes and then another table which will house the recipe's ingredients and the quantities and measurements of these ingredients. Format similar to below.

Recipes
- ID
- Recipe Name
- Recipe Yield
- Measurement Type
- Description
- Notes (JSON Formatted)
- Steps (JSON Formatted)
- Public, Private, Unlisted (Determined by value of 0, 1, 2)
- Owner (Will be corresponding to a user) - This will be future
- Category

Recipe_Ingredients
- ID
- Recipe_ID  -> Foreign Key to recipes
- Ingredient_ID -> Foreign Key to ingredients
- Quantity
- Measurement_Type

**Comment by ZachSellman** [comment]
Okay here's my notes/changes on Recipes table:

Recipes

ID
Recipe Name
Recipe Yield
~~Measurement Type~~ -> ~~We can separate this into solid/liquid and create lists of accepted measurements (i.e tsp, oz, etc)~~
`EDIT: I think I see what you're saying with this; I'd propose changing it to "Yield Type" to avoid confusion with the ingredients measurements.`

Description
Notes (JSON Formatted)
Steps (JSON Formatted)

Public, Private, Unlisted (Determined by value of 0, 1, 2) `->unsure of what unlisted means in this context; if it's not meant to be public it can only be private, and vice versa. Even if it's unfinished it would still just be a private recipe.`

Owner (Will be corresponding to a user) - This will be future `-> This will be possible through Django admin panel very easily; if you DO want to create additional users and allow them to log in/change account settings/modify recipes that will be a larger addition; this decision can be made later, as in the meantime the recipes will only be able to be created through the Django admin panel.`

Category `-> I'll need a list of categories for this field. This might be better as a "tag" option? As in recipe is for pork tacos, so tags could be "pork", "taco", "Mexican", etc. This would allow searches via tags instead of trying to come up with comprehensive categories.`

**Comment by jeffhennen** [comment]
Yeah, so the Measurement Type, that is something that we can just set at the time generating the recipe. This will be all of the ones you had mentioned. (tsp, oz, lbs, kg, g, etc). They would be defined at the point of entering in the recipe information or entering in an ingredient for the recipe. We should just include this as is now and then later down the line we can make use of it further by doing computation based on the conversion ratios of measurements.

The Public, Private, Unlisted. Unlisted would be associated and used for the recipe history, this is where you would have a way to reference a recipe directly by maybe url or link but it is not broadcasted for the public. The reasoning behind this is because when you are generating a recipe you would want to be able to also see the previous versions of the recipe to see what you have tried. This is regarding: Issue https://github.com/ZachSellman/hennen_recipes/issues/17 recipe history table. The thoughts is that you would have a recipe that you can look up and then see a specified number of unlisted recipes that were used to make this recipe.

The owner, I agree we can leave this out for now but would be something that we would want to include in future. Seperate low priority issue.

Yeah, category is probably not needed if we add in tags.

The Tags I think would be good to add in for future searching but we can seperate out to a different lower priority issue. this would require multiple tables, one for defining a tag, and then another for defining all the tags a recipe has as it would be unkown how many tags you would have.
